name: FF14 Risingstone Sign Tasks
author: StarHeartHunt <starheart233@gmail.com>
description: auto finish sign tasks of ff14 risingstone
inputs:
  cookie:
    description: The Cookie header set by risingstone server
    required: true
  user_agent:
    description: The User-Agent header when login into risingstone
    required: true
  base_url:
    description: The API domain of risingstone
    required: false
  comment_content:
    description: The html content of the comment
    required: false
  like_post_id:
    description: The post id to send like
    required: false
  comment_post_id:
    description: The post id to send comment
    required: false
  check_house_remain:
    description: Whether to check the countdown to the role's house destruction
    required: false
  get_sign_reward:
    description: Whether to auto get the sign reward
    required: false

runs:
  using: docker
  image: Dockerfile
branding:
  icon: box
  color: orange
