name: Daily Tasks

on:
  schedule:
    # Runs at 10:30 am UTC+8 every day
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  run-tasks:
    name: Run FF14 Risingstone Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker://ghcr.io/starhearthunt/ff14risingstone_sign_task:master
        with:
          cookie: ${{ secrets.ff14risingstones=s%3A5QO6uK81g70VTLDPKEu2CJkmp6SwAHEh.3WdLy%2FPHfE7elyJtgDUsyYF1%2Byvi%2F9LI54pSxe4p%2B7c }}
          user_agent: ${{ secrets.Mozilla/5.0 (Linux; Android 15; Redmi K30 Pro Zoom Edition Build/AQ3A.240912.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.86 Mobile Safari/537.36 DaoYu/9.5.4 }}
